
source = ~/dotfiles/.config/hypr/appearance.conf
source = ~/dotfiles/.config/hypr/bind.conf
source = ~/dotfiles/.config/hypr/monitor.conf
source = ~/dotfiles/.config/hypr/peripheral.conf

# Default Applications

$terminal = kitty
$fileManager = dolphin
$menu = bemenu-run -c -W 0.25 -l 10 --fb '##303446' --ff '##c6d0f5' --nb '##303446' --nf '##c6d0f5' --tb '##303446' --hb '##303446' --tf '##e78284' --hf '##e5c890' --af '##c6d0f5' --ab '##303446'

# Autostart
exec-once = hyprpaper & waybar
exec-once = dunst
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Vital Bindings

$mainMod = SUPER
bind = $mainMod, t, exec, $terminal
bind = $mainMod, r, exec, $menu
bind = $mainMod, e, exec, $fileManager

