
source = $HOME/dotfiles/.config/hypr/animations.conf
source = $HOME/dotfiles/.config/hypr/appearance.conf
source = $HOME/dotfiles/.config/hypr/bind.conf
source = $HOME/dotfiles/.config/hypr/monitor.conf
source = $HOME/dotfiles/.config/hypr/peripheral.conf
source = $HOME/dotfiles/.config/hypr/windowrule.conf

env = LANG, en_US.UTF-8

# Default Applications

$terminal = kitty
$fileManager = dolphin

$menu = $HOME/dotfiles/.config/bemenu/run.sh

# Autostart
exec-once = hyprpaper & ignis init & dunst
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = easyeffects -w

# Vital Bindings

$mainMod = SUPER
bind = $mainMod, t, exec, $terminal
bind = $mainMod, r, exec, $menu
bind = $mainMod, e, exec, $fileManager

# Fixes the empty "open with" in Dolphin
env = XDG_MENU_PREFIX,arch-
