input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

device {
    name = beken-2.4g-wireless-device-1
    sensitivity = 0
    accel_profile = flat
}
