# Ignore maximize requests from apps. You'll probably like this.
# windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
# windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Makes pavucontrol to floating
windowrule {
  name = float_pavucontrol
  match:class = org.pulseaudio.pavucontrol
  float = 1
}

# Makes Firefox Profile  window to floating
windowrule {
  name = float_firefox_profiles
  match:title = (Firefox - Choose User Profile)
  float = 1
}

# Steam interrupts fullscreen games on reset
# This forces hyprland to workspace 1
windowrule {
  name = workspace_steam
  match:class = (.*)(steam)$
  workspace = 1 silent
  no_initial_focus = 1
}
